[package]
name = "celebrum-ai-shared"
version = "0.1.0"
edition = "2021"
authors = ["ArbEdge Team"]
description = "Shared utilities and types for ArbEdge Arbitrage Platform"

[lib]
crate-type = ["rlib"]

[dependencies]
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.10", features = ["v4"] }

# Async support
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# Utilities
rust_decimal = { version = "1.0", features = ["serde-float"] }
once_cell = "1.18"
thiserror = "1.0"
anyhow = "1.0"

# Logging
log = "0.4"