packages:
  - packages/*
  - packages/core
  - packages/shared
  - packages/web
  - packages/discord-bot
  - packages/telegram-bot

catalog:
  typescript: 5.8.3
  '@types/node': 24.0.3
  wrangler: ^4.20.5
  oxlint: ^1.1.0
  drizzle-orm: ^0.44.2
  drizzle-kit: ^0.31.1

link-workspace-packages: true

overrides:
  esbuild@<=0.24.2: '>=0.25.0'

publishConfig:
  registry: https://registry.npmjs.org/
