name = "arb-edge"
compatibility_date = "2025-05-06"
compatibility_flags = ["nodejs_compat"]
main = "build/worker/shim.mjs"

# Build configuration for Rust
[build]
command = "chmod +x build.sh && ./build.sh"

# KV Namespace for storing configuration and state
[[kv_namespaces]]
binding = "ArbEdgeKV"
id = "1018c576bf664c15afe0c53d85df8ed0"
preview_id = "9db67fd132d64e93bcdf3cebebd07bc6"

# D1 Database for structured data
[[d1_databases]]
binding = "ArbEdgeD1"
database_name = "prod-arb-edge"
database_id = "879bf844-93b2-433d-9319-6e6065bbfdfd"
migrations_dir = "sql/migrations"

# Durable Object migrations - Delete old PositionsManager
[[migrations]]
tag = "v1"
deleted_classes = ["PositionsManager"]

# Cron Triggers for scheduled tasks
[triggers]
crons = ["*/5 * * * *"] # Run every 5 minutes

# Environment variables
[vars]
ENVIRONMENT = "production"
SUPER_ADMIN_USER_ID = "1082762347"

# Development environment variables
[env.dev]
name = "arb-edge-dev"
[env.dev.vars]
ENVIRONMENT = "development"
SUPER_ADMIN_USER_ID = "1082762347"

# Secrets are now stored as regular Worker secrets
# Use: wrangler secret put TELEGRAM_BOT_TOKEN

# Enable observability
[observability]
enabled = true

[observability.logs]
enabled = true
