name = "arb-edge"
compatibility_date = "2025-05-06"
compatibility_flags = ["nodejs_compat"]
main = "build/worker/shim.mjs"

# Build configuration for Rust
[build]
command = "cargo install worker-build && worker-build --release"

# KV Namespace for storing configuration and state
kv_namespaces = [
  { binding = "ArbEdgeKV", id = "1018c576bf664c15afe0c53d85df8ed0", preview_id = "9db67fd132d64e93bcdf3cebebd07bc6" }
]

# D1 Database for structured data
[[d1_databases]]
binding = "ArbEdgeDB"
database_name = "arb-edge-db"
database_id = "placeholder-db-id" # Will be set after creating the database

# Cron Triggers for scheduled tasks
[triggers]
crons = ["*/5 * * * *"] # Run every 5 minutes

# Environment variables
[vars]
ENVIRONMENT = "production"
USDT_AMOUNT = "10"
BYBIT_LEVERAGE = "20"
BINANCE_LEVERAGE = "20"

# Development environment variables
[env.dev]
name = "arb-edge-dev"
[env.dev.vars]
ENVIRONMENT = "development"

# Secrets (to be added via wrangler)
# wrangler secret put BYBIT_API_KEY
# wrangler secret put BYBIT_API_SECRET
# wrangler secret put BINANCE_API_KEY
# wrangler secret put BINANCE_API_SECRET
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put TELEGRAM_CHAT_ID

# Enable observability
[observability]
enabled = true

[observability.logs]
enabled = true
