name = "arb-edge"
main = "src/index.ts"
compatibility_date = "2025-05-06"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for storing configuration and state
kv_namespaces = [
  { binding = "ArbEdgeKV", id = "1018c576bf664c15afe0c53d85df8ed0", preview_id = "9db67fd132d64e93bcdf3cebebd07bc6" }
]

# Durable Objects for managing state
[durable_objects]
bindings = [
  { name = "POSITIONS", class_name = "PositionsManager" }
]

# Add Durable Object migrations
[[migrations]]
tag = "v1" # Initial migration tag
new_classes = [ "PositionsManager" ]

# Cron Triggers for scheduled tasks
[triggers]
crons = ["*/5 * * * *"] # Run every 5 minutes

# Environment variables
[vars]
ENVIRONMENT = "production"
USDT_AMOUNT = "10"
BYBIT_LEVERAGE = "20"
BINANCE_LEVERAGE = "20"

# Development environment variables
[env.dev]
name = "arb-edge-dev"
[env.dev.vars]
ENVIRONMENT = "development"

# Secrets (to be added via wrangler)
# wrangler secret put BYBIT_API_KEY
# wrangler secret put BYBIT_API_SECRET
# wrangler secret put BINANCE_API_KEY
# wrangler secret put BINANCE_API_SECRET
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put TELEGRAM_CHAT_ID

# Enable observability logs (Wrangler v3.38.0+)
[observability.logs]
enabled = true
