[package]
name = "celebrum-ai-discord-bot"
version = "0.1.0"
edition = "2021"
authors = ["ArbEdge Team"]
description = "Discord Bot for ArbEdge Arbitrage Platform"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Cloudflare Workers runtime
worker = "0.3"

# Async support
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# HTTP client
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging
console_error_panic_hook = "0.1"
console_log = "1.0"
log = "0.4"