[package]
name = "celebrum-ai-worker"
version = "0.1.0"
edition = "2021"
authors = ["ArbEdge Team"]
description = "Core Worker for ArbEdge Arbitrage Platform"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Cloudflare Workers runtime
worker = { version = "0.3", features = ["d1", "queue"] }

# Async support
tokio = { version = "1.0", features = ["sync", "macros", "io-util", "rt", "time"] }
futures = "0.3"

# HTTP client
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.10", features = ["v4"] }

# Database (non-WASM only)

# Cryptography
sha2 = "0.10"
aes-gcm = "0.10"
base64 = "0.21"
ring = "0.16"

# Utilities
rust_decimal = { version = "1.0", features = ["serde-float"] }
async-trait = "0.1"
rand = "0.8"
once_cell = "1.18"

# Logging
log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "macros", "migrate", "chrono", "uuid"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8", features = ["getrandom"] }
uuid = { version = "1.10", features = ["v4", "js"] }