name = "dev-celebrum-ai"
compatibility_date = "2024-05-18"
compatibility_flags = ["nodejs_compat"]
account_id = "12c131cfa275bfa596ed5f840a2de74f"

main = "src/container-entry.ts"

[[containers]]
 name = "main"
image = "docker.io/library/node:20-slim"
command = ["pnpm", "start"]
class_name = "MainContainer"

[site]
bucket = "../../packages/web/dist"

# KV Namespaces
[[kv_namespaces]]
binding = "ArbEdgeKV"
id = "975cbb73bbc047d5980d4c22c58e1cc7"
preview_id = "9db67fd132d64e93bcdf3cebebd07bc6"

[[kv_namespaces]]
binding = "PROD_BOT_MARKET_CACHE"
id = "0b76a94e2ab34f7b94bfb9268d9c6b7f"
preview_id = "9db67fd132d64e93bcdf3cebebd07bc6"

[[kv_namespaces]]
binding = "PROD_BOT_SESSION_STORE"
id = "3c74b10792214176a876be682d147871"
preview_id = "9db67fd132d64e93bcdf3cebebd07bc6"

# D1 Database
[[d1_databases]]
binding = "ArbEdgeD1"
database_name = "prod-celebrum-ai"
database_id = "879bf844-93b2-433d-9319-6e6065bbfdfd"
migrations_dir = "../db/sql/migrations"

# R2 Buckets
[[r2_buckets]]
binding = "ArbEdgeR2"
bucket_name = "prod-celebrum-ai"

[[r2_buckets]]
binding = "ArbEdgeR2_Analytics"
bucket_name = "prod-celebrum-ai-analytics"

# Environment Variables
[vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"

# Development configuration
[dev]