name = "dev-celebrum-ai-telegram-bot"
compatibility_date = "2024-05-18"
compatibility_flags = ["nodejs_compat"]
account_id = "12c131cfa275bfa596ed5f840a2de74f"

main = "src/index.ts"

# KV Namespaces
[[kv_namespaces]]
binding = "ArbEdgeKV"
id = "975cbb73bbc047d5980d4c22c58e1cc7"
preview_id = "9db67fd132d64e93bcdf3cebebd07bc6"

[[kv_namespaces]]
binding = "PROD_BOT_MARKET_CACHE"
id = "0b76a94e2ab34f7b94bfb9268d9c6b7f"
preview_id = "9db67fd132d64e93bcdf3cebebd07bc6"

[[kv_namespaces]]
binding = "PROD_BOT_SESSION_STORE"
id = "3c74b10792214176a876be682d147871"
preview_id = "9db67fd132d64e93bcdf3cebebd07bc6"