[package]
name = "arb-edge-db"
version = "0.1.0"
edition = "2021"
authors = ["ArbEdge Team"]
description = "Database layer for ArbEdge Arbitrage Platform"

[lib]
crate-type = ["rlib"]

[dependencies]
# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "macros", "migrate", "chrono", "uuid"] }

# Async support
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4"] }

# Utilities
rust_decimal = { version = "1.0", features = ["serde-float"] }
thiserror = "1.0"
anyhow = "1.0"

# Logging
log = "0.4"