name: CI/CD & Security Analysis

# CI Strategy:
# - Run tests and security analysis on ALL branches and PRs
# - Deploy to production only from main branch
on:
  push:
    branches: ["**"]  # Run on all branches
  pull_request:
    branches: ["**"]  # Run on PRs to all branches
  workflow_dispatch:

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, rust-src

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Node.js (for wrangler)
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install wrangler
        run: npm install -g wrangler@latest

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run linter
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --verbose

      - name: Build for WASM
        run: cargo build --target wasm32-unknown-unknown --release

      - name: Test wrangler build
        run: wrangler deploy --dry-run

  codeql:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    needs: test
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: rust
        env:
          CODEQL_ENABLE_EXPERIMENTAL_FEATURES: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  deploy:
    name: Deploy to Cloudflare
    needs: [test, codeql]
    # Only deploy from main branch on push (not PRs)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup Node.js (for wrangler)
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Workers
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
